import http from 'node:http';
import crypto from 'node:crypto';
import { db, decode, encode, hashPin, now, uuid, verifyPin } from './database.js';

const tables = new Set(['trial_files', 'gipod_codes', 'gipod_code_requests', 'app_file_logs', 'app_user_activity', 'app_shipment_activity', 'app_eod_cleanups', 'coordinator_auto_queue']);
const roles = new Set(['Admin', 'Lead', 'Device Coordinator', 'Shipper', 'Device Systems Specialist']);
const managers = new Set(['Admin', 'Lead']);
const profile = (u) => ({ id: u.id, firstName: u.first_name, lastName: u.last_name, role: u.role, permissions: JSON.parse(u.permissions), weeklySchedule: JSON.parse(u.weekly_schedule), trainedDevices: JSON.parse(u.trained_devices), isNewHire: Boolean(u.is_new_hire), dashboardLayout: u.dashboard_layout, isLoggedIn: Boolean(u.is_logged_in) });
const actor = (id, manager = false) => { const u = db.prepare('SELECT * FROM app_users WHERE id=? AND is_active=1').get(id); if (!u || (manager && !managers.has(u.role))) throw new Error(manager ? 'Only Admin and Lead users can perform this action.' : 'User not found.'); return u; };
const sessionUser = (token, specialist = false) => { const u = db.prepare(`SELECT u.* FROM sessions s JOIN app_users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>? AND u.is_active=1`).get(token, now()); if (!u || (specialist && u.role !== 'Device Systems Specialist')) throw new Error(specialist ? 'Only Device Systems Specialists can perform this action.' : 'Your session has expired. Please log in again.'); return u; };
const title = (s) => String(s || '').trim().replace(/\b\w/g, c => c.toUpperCase());

function tableRequest(table, method, body) {
  if (!tables.has(table)) throw new Error('Unknown table.');
  const filters = body.filters || [];
  const clauses = [], params = [];
  for (const f of filters) {
    if (!/^[a-z_]+$/.test(f.column)) throw new Error('Invalid filter.');
    if (f.op === 'eq') { clauses.push(`${f.column}=?`); params.push(f.value); }
    if (f.op === 'in') { clauses.push(`${f.column} IN (${f.value.map(() => '?').join(',')})`); params.push(...f.value); }
    if (f.op === 'not' && f.operand === 'is' && f.value === null) clauses.push(`${f.column} IS NOT NULL`);
  }
  const where = clauses.length ? ` WHERE ${clauses.join(' AND ')}` : '';
  if (method === 'POST') {
    const order = (body.orders || []).filter(x => /^[a-z_]+$/.test(x.column)).map(x => `${x.column} ${x.ascending ? 'ASC' : 'DESC'}`).join(', ');
    const rows = db.prepare(`SELECT * FROM ${table}${where}${order ? ` ORDER BY ${order}` : ''}${body.limit ? ` LIMIT ${Number(body.limit)}` : ''}`).all(...params).map(decode);
    return body.head ? null : rows;
  }
  if (method === 'PUT') {
    const rows = Array.isArray(body.rows) ? body.rows : [body.rows];
    const columns = new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(column => column.name));
    db.exec('BEGIN'); try { rows.forEach(raw => { const stamp = now(); const values = { id: uuid(), ...raw }; if (columns.has('created_at')) values.created_at ||= stamp; if (columns.has('updated_at')) values.updated_at ||= stamp; if (columns.has('shipped_at')) values.shipped_at ||= stamp; const row = encode(values); const keys = Object.keys(row).filter(key => columns.has(key)); db.prepare(`INSERT INTO ${table} (${keys.join(',')}) VALUES (${keys.map(() => '?').join(',')})`).run(...keys.map(k => row[k])); }); db.exec('COMMIT'); } catch (error) { db.exec('ROLLBACK'); throw error; } return null;
  }
  if (method === 'PATCH') { const row = encode({ ...body.rows, updated_at: now() }); const keys = Object.keys(row); db.prepare(`UPDATE ${table} SET ${keys.map(k => `${k}=?`).join(',')}${where}`).run(...keys.map(k => row[k]), ...params); return null; }
  db.prepare(`DELETE FROM ${table}${where}`).run(...params); return null;
}

function rpc(name, p) {
  if (name === 'login_app_user') { const u = db.prepare('SELECT * FROM app_users WHERE lower(first_name)=lower(?) AND lower(last_name)=lower(?) AND is_active=1').get(p.p_first_name?.trim(), p.p_last_name?.trim()); if (!u || !/^\d{4}$/.test(p.p_pin) || !verifyPin(p.p_pin, u.pin_hash)) return null; const token = crypto.randomBytes(32).toString('hex'); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token, u.id, new Date(Date.now() + 43200000).toISOString()); db.prepare('UPDATE app_users SET is_logged_in=1,last_login_at=?,updated_at=? WHERE id=?').run(now(), now(), u.id); return { ...profile(u), isLoggedIn: true, deviceRequestToken: token }; }
  if (name === 'set_app_user_login_status') { db.prepare(`UPDATE app_users SET is_logged_in=?, ${p.p_logged_in ? 'last_login_at' : 'last_logout_at'}=?,updated_at=? WHERE id=?`).run(p.p_logged_in ? 1 : 0, now(), now(), p.p_user_id); return null; }
  if (name === 'list_device_specialists' || name === 'list_device_coordinators') return db.prepare('SELECT id,first_name,last_name,trained_devices,is_new_hire,is_logged_in FROM app_users WHERE role=? AND is_active=1 ORDER BY last_name,first_name').all(name.endsWith('specialists') ? 'Device Systems Specialist' : 'Device Coordinator').map(decode);
  if (name === 'list_app_users') { actor(p.p_actor_id, true); return db.prepare('SELECT id,first_name,last_name,role,permissions,weekly_schedule,trained_devices,is_new_hire,dashboard_layout,is_active,is_logged_in,last_login_at,last_logout_at,created_at,updated_at FROM app_users ORDER BY last_name,first_name').all().map(decode); }
  if (name === 'list_app_user_login_statuses') { actor(p.p_actor_id, true); return db.prepare('SELECT id,is_logged_in,last_login_at,last_logout_at FROM app_users WHERE is_active=1').all().map(decode); }
  if (name === 'create_app_user') { actor(p.p_actor_id, true); if (!/^\d{4}$/.test(p.p_pin)) throw new Error('PIN must be exactly 4 digits.'); if (!roles.has(p.p_role)) throw new Error('Invalid role.'); if (db.prepare('SELECT 1 FROM app_users').all().some(() => false)) {} const duplicatePin = db.prepare('SELECT pin_hash FROM app_users').all().some(x => verifyPin(p.p_pin, x.pin_hash)); if (duplicatePin) throw new Error('A user with that name or PIN already exists.'); const id=uuid(), stamp=now(); try { db.prepare(`INSERT INTO app_users(id,first_name,last_name,role,pin_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).run(id,title(p.p_first_name),title(p.p_last_name),p.p_role,hashPin(p.p_pin),stamp,stamp); } catch { throw new Error('A user with that name or PIN already exists.'); } return profile(db.prepare('SELECT * FROM app_users WHERE id=?').get(id)); }
  if (name === 'delete_app_user') { actor(p.p_actor_id, true); if (p.p_actor_id === p.p_user_id) throw new Error('You cannot remove your own user while logged in.'); db.prepare('DELETE FROM app_users WHERE id=?').run(p.p_user_id); return null; }
  if (name === 'get_app_user_profile') { const a=actor(p.p_actor_id), u=actor(p.p_user_id); if (a.id!==u.id&&!managers.has(a.role)) throw new Error('Only Admin, Lead, or the profile owner can view this profile.'); return profile(u); }
  if (name.startsWith('update_app_user_') || name === 'update_own_app_user_pin') return updateUser(name,p);
  if (name === 'list_app_user_activity') { const a=actor(p.p_actor_id); if(a.id!==p.p_user_id&&!managers.has(a.role)) throw new Error('Not authorized.'); return db.prepare('SELECT action,activity_date,count(*) count FROM app_user_activity WHERE user_id=? GROUP BY action,activity_date ORDER BY activity_date DESC').all(p.p_user_id); }
  if (name === 'list_team_user_activity') { actor(p.p_actor_id,true); return db.prepare(`SELECT a.user_id,u.first_name,u.last_name,u.role,a.action,a.activity_date,count(*) count,max(a.created_at) latest_at FROM app_user_activity a JOIN app_users u ON u.id=a.user_id GROUP BY a.user_id,a.action,a.activity_date ORDER BY a.activity_date DESC`).all(); }
  if (name.includes('device_request')) return deviceRpc(name,p);
  if (name === 'claim_next_gipod_code') { const code=db.prepare("SELECT * FROM gipod_codes WHERE used_on='' ORDER BY created_at LIMIT 1").get(); if(!code) throw new Error('No unused GIPOD codes are available.'); db.prepare('UPDATE gipod_codes SET used_on=?,used_date=?,updated_at=? WHERE id=?').run(p.p_crm_number,p.p_used_date||now().slice(0,10),now(),code.id); db.prepare('UPDATE trial_files SET gipod_code=?,updated_at=? WHERE id=?').run(code.code,now(),p.p_file_id); return code.code; }
  if (name === 'request_gipod_code') { const u=actor(p.p_actor_id), f=db.prepare('SELECT * FROM trial_files WHERE id=?').get(p.p_file_id); if(!f) throw new Error('File not found.'); if(db.prepare("SELECT 1 FROM gipod_code_requests WHERE file_id=? AND status='pending'").get(f.id)) throw new Error('This file already has a pending request.'); db.prepare(`INSERT INTO gipod_code_requests(id,file_id,requester_user_id,requester_name,first_name,last_name,device,crm_number,reason,requested_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(uuid(),f.id,u.id,`${u.first_name} ${u.last_name}`,f.first_name,f.last_name,f.device,(f.crm_link.match(/\d{5}/)||[''])[0],p.p_reason,p.p_requested_at||now(),now()); return null; }
  if (name === 'approve_gipod_code_request') { actor(p.p_actor_id,true); const r=db.prepare("SELECT * FROM gipod_code_requests WHERE id=? AND status='pending'").get(p.p_request_id); if(!r) return null; const code=rpc('claim_next_gipod_code',{p_file_id:r.file_id,p_crm_number:r.crm_number,p_used_date:p.p_used_date}); db.prepare("UPDATE gipod_code_requests SET status='approved',gipod_code=?,resolved_by_user_id=?,resolved_at=?,updated_at=? WHERE id=?").run(code,p.p_actor_id,p.p_resolved_at||now(),now(),r.id); return code; }
  throw new Error(`Unknown operation: ${name}`);
}

function updateUser(name,p) { const target=p.p_user_id; if(name==='update_own_app_user_pin'){ const u=actor(target); if(!verifyPin(p.p_current_pin,u.pin_hash)) throw new Error('Current PIN is incorrect.'); if(!/^\d{4}$/.test(p.p_new_pin)) throw new Error('PIN must be exactly 4 digits.'); db.prepare('UPDATE app_users SET pin_hash=?,updated_at=? WHERE id=?').run(hashPin(p.p_new_pin),now(),target); return profile(db.prepare('SELECT * FROM app_users WHERE id=?').get(target)); } const a=actor(p.p_actor_id), u=actor(target); if(a.id!==u.id&&!managers.has(a.role)) throw new Error('Not authorized.'); let col,val; if(name.endsWith('_role')){ if(!managers.has(a.role)||!roles.has(p.p_role)) throw new Error('Invalid role.'); col='role';val=p.p_role;} else if(name.endsWith('_pin')){ if(!managers.has(a.role)||!/^\d{4}$/.test(p.p_pin)) throw new Error('PIN must be exactly 4 digits.'); col='pin_hash';val=hashPin(p.p_pin);} else if(name.endsWith('_schedule')){col='weekly_schedule';val=JSON.stringify(p.p_schedule||{});} else if(name.endsWith('_trained_devices')){col='trained_devices';val=JSON.stringify(p.p_trained_devices||[]);db.prepare('UPDATE app_users SET is_new_hire=? WHERE id=?').run(p.p_is_new_hire?1:0,target);} else {col='dashboard_layout';val=p.p_dashboard_layout;} db.prepare(`UPDATE app_users SET ${col}=?,updated_at=? WHERE id=?`).run(val,now(),target); return profile(db.prepare('SELECT * FROM app_users WHERE id=?').get(target)); }
function deviceRpc(name,p){ const u=sessionUser(p.p_session_token,name==='claim_device_request'||name==='complete_device_request'); if(name==='list_device_requests') return db.prepare("SELECT * FROM device_requests ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'claimed' THEN 1 ELSE 2 END, requested_at DESC").all(); if(name==='create_device_request'){if(!['Admin','Lead','Device Systems Specialist'].includes(u.role)) throw new Error('Not authorized.'); const id=uuid(),stamp=p.p_requested_at||now();db.prepare(`INSERT INTO device_requests(id,crm_link,device_number,internal_serial_number,request_type,apps_wanted,notes,requester_user_id,requester_name,requester_role,requested_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,p.p_crm_link,p.p_device_number,p.p_internal_serial_number,p.p_request_type,p.p_apps_wanted||'',p.p_notes||'',u.id,`${u.first_name} ${u.last_name}`,u.role,stamp,stamp,stamp);return id;} const r=db.prepare('SELECT * FROM device_requests WHERE id=?').get(p.p_request_id);if(!r)return null;if(name==='claim_device_request'){if(r.status!=='pending')return null;db.prepare("UPDATE device_requests SET status='claimed',claimed_by_user_id=?,claimed_by_name=?,claimed_at=?,updated_at=? WHERE id=?").run(u.id,`${u.first_name} ${u.last_name}`,p.p_claimed_at||now(),now(),r.id);}else{if(r.claimed_by_user_id&&r.claimed_by_user_id!==u.id)throw new Error('This request is claimed by another specialist.');db.prepare("UPDATE device_requests SET status='complete',claimed_by_user_id=?,claimed_by_name=?,claimed_at=coalesce(claimed_at,?),completed_by_user_id=?,completed_by_name=?,completed_at=?,updated_at=? WHERE id=?").run(u.id,`${u.first_name} ${u.last_name}`,p.p_completed_at||now(),u.id,`${u.first_name} ${u.last_name}`,p.p_completed_at||now(),now(),r.id);}return r.id;}

export function createServer() { return http.createServer(async (req,res)=>{ res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,PATCH,DELETE,OPTIONS');if(req.method==='OPTIONS'){res.writeHead(204).end();return;} try{let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):{};let data;if(req.url==='/api/health')data={status:'ok'};else {const table=req.url.match(/^\/api\/tables\/([a-z_]+)$/)?.[1];const operation=req.url.match(/^\/api\/rpc\/([a-z_]+)$/)?.[1];if(table)data=tableRequest(table,req.method,body);else if(operation)data=rpc(operation,body);else throw new Error('Not found.');}res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({data}));}catch(e){console.error(e);res.writeHead(400,{'Content-Type':'application/json'}).end(JSON.stringify({error:e.message}));}}); }
